### PR TITLE
Miguel branch 1

### PR DESCRIPTION
**Pull request by MiguelS-hub**

### CODE REVIEW

**Review by Rafquadros22 — COMMENTED** [review]
g

**Comment by MiguelS-hub** [comment]
hi

**Review by uwaiskhan — APPROVED** [review]

**Review by Jen042823 — COMMENTED** [review]
Already merged html from Raf

**Review by MiguelS-hub — COMMENTED** [review]
lol

**Review by Rafquadros22 — COMMENTED** [review]
g

**Pull request merged**
